name: BianCheng Deploy
on: [push]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Build & Deploy
        uses: wswplay/wswplay.github.io@main
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BUILD_SCRIPT: yarn && yarn build
          BUILD_DIR: docs/.vuepress/dist/
